### ISSUE TITLE
--show-exited not working

### ISSUE THREAD

**Issue by KAGEYAM4** [Tomas-M/iotop#76] opened 2024-11-17 01:25 UTC
After a while, if process is closed it gets removed from the list. Using `e` to toggle show-exited does not work.

**Comment by bbonev** [comment] 2024-11-18 11:36
Yes, this is by design. Exited processes are not kept forever. Only as long as there is some graph data for them.

**Comment by KAGEYAM4** [comment] 2024-11-18 12:52
> Note that keeping them forever will become problematic after the PID is reused for a new process.

Makes sense.


By the way, do you know of any way i can achieve this? I want to track network usage per application over a period of time. so that i can see which application is writing/reading moset to the SSD. (i.e, usage data in current session, last session, nth session.  -- similar to `journalctl --list-boots` )

**Comment by bbonev** [comment] 2024-12-26 13:34
I think that you can run iotop in batch mode, but then you need to write a script to aggregate the output and produce the report you want. I think that grouping by cmd will produce most meaningful result.

But there is nothing to be changed in iotop to achieve this, so I am closing the issue. Feel free to reopen in case I am missing something

**Closed** 2024-12-26 13:34 UTC

**Comment by Kiisu-Master** [comment] 2026-03-08 17:41
This makes the setting usesless for me, I really hoped it would show exited processes forever :(
I'm not constantly looking at the program, so it would be nice if the accumulated data would stay.
This is just weird, even the total disk writes at the top goes back down when the programs disappear from the list.

**Comment by bbonev** [comment] 2026-03-09 20:06
Thanks for reporting this.

If you can provide infinite amount of memory to `iotop`, then it will be able to keep the data for all exited processes forever.

People tend to start monitoring tools and leave them running for long periods of time, hence the need to limit the amount of used memory by discarding old data. On a busy system that will sooner or later lead to an OOM, which I believe, is not a desired result...

**Comment by Kiisu-Master** [comment] 2026-03-09 21:31
Would it be possible to make it configurable how long dead processes are kept in the list?
